server:
  port: 8080


# CONECCION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.67:5433/GOTALENT
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true

# ESPECIFICACIONES DE KAFKA
#  kafka:
#    bootstrap-servers: broker:9093
#    consumer:
#      group-id: myGroup
