server:
  port: 8080
springdoc:
  packages-to-scan: com.righttek.es.ubicacion.controller
  pathsToMatch: /v1, /api/es/ubicacion/**

# CONECCION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.67:5433/GOTALENT
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
