server:
  port: 8085

# CONECCION A BASE DE DATOS
spring:
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=GotalentRTQA
    username: sa
    password: Pa$$w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
# Hibernate ddl auto (create, create-drop, validate, update)
  hibernate:
	  dialect: org.hibernate.dialect.MySQLInnoDBDialect

# SERVICIOS A CONSUMIR
